In [31]:
import pandas as pd
import numpy as np
data1=pd.read_csv("D://train.csv")

In [38]:
data2=data1.interpolate()

In [39]:
data2.head(40)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.000000,14.000000,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,10.000000,14.600000,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.000000,15.200000,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,8.000000,15.800000,7969
5,1000003,P00193542,M,26-35,15,A,3,0,1,2.000000,16.400000,15227
6,1000004,P00184942,M,46-50,7,B,2,1,1,8.000000,17.000000,19215
7,1000004,P00346142,M,46-50,7,B,2,1,1,15.000000,15.285714,15854
8,1000004,P0097242,M,46-50,7,B,2,1,1,16.000000,13.571429,15686
9,1000005,P00274942,M,26-35,20,A,1,1,8,13.500000,11.857143,7871
10,1000005,P00251242,M,26-35,20,A,1,1,5,11.000000,10.142857,5254
11,1000005,P00014542,M,26-35,20,A,1,1,8,8.000000,8.428571,3957
12,1000005,P00031342,M,26-35,20,A,1,1,8,5.000000,6.714286,6073
13,1000005,P00145042,M,26-35,20,A,1,1,1,2.000000,5.000000,15665
14,1000006,P00231342,F,51-55,9,A,1,0,5,8.000000,14.000000,5378
15,1000006,P00190242,F,51-55,9,A,1,0,4,5.000000,9.000000,2079
16,1000006,P0096642,F,51-55,9,A,1,0,2,3.000000,4.000000,13055
17,1000006,P00058442,F,51-55,9,A,1,0,5,14.000000,10.000000,8851
18,1000007,P00036842,M,36-45,1,B,1,1,1,14.000000,16.000000,11788
19,1000008,P00249542,M,26-35,12,C,4+,1,1,5.000000,15.000000,19614
20,1000008,P00220442,M,26-35,12,C,4+,1,5,14.000000,14.800000,8584
21,1000008,P00156442,M,26-35,12,C,4+,1,8,12.500000,14.600000,9872
22,1000008,P00213742,M,26-35,12,C,4+,1,8,11.000000,14.400000,9743
23,1000008,P00214442,M,26-35,12,C,4+,1,8,9.500000,14.200000,5982
24,1000008,P00303442,M,26-35,12,C,4+,1,1,8.000000,14.000000,11927
25,1000009,P00135742,M,26-35,17,C,0,0,6,8.000000,14.000000,16662
26,1000009,P00039942,M,26-35,17,C,0,0,8,11.000000,14.000000,5887
27,1000009,P00161442,M,26-35,17,C,0,0,5,14.000000,14.000000,6973
28,1000009,P00078742,M,26-35,17,C,0,0,5,8.000000,14.000000,5391
29,1000010,P00085942,F,36-45,1,B,4+,1,2,4.000000,8.000000,16352
30,1000010,P00118742,F,36-45,1,B,4+,1,5,11.000000,8.142857,8886
31,1000010,P00297942,F,36-45,1,B,4+,1,8,8.666667,8.285714,5875
32,1000010,P00266842,F,36-45,1,B,4+,1,5,6.333333,8.428571,8854
33,1000010,P00058342,F,36-45,1,B,4+,1,3,4.000000,8.571429,10946
34,1000010,P00032442,F,36-45,1,B,4+,1,5,4.000000,8.714286,5152
35,1000010,P00105942,F,36-45,1,B,4+,1,5,4.000000,8.857143,7089
36,1000010,P00182642,F,36-45,1,B,4+,1,2,4.000000,9.000000,12909
37,1000010,P00186942,F,36-45,1,B,4+,1,5,12.000000,12.000000,8770
38,1000010,P00155442,F,36-45,1,B,4+,1,1,11.000000,15.000000,15212
39,1000010,P00221342,F,36-45,1,B,4+,1,1,2.000000,5.000000,15705

In [62]:
data2.dropna()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.000000,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,10.0,14.600000,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,15.200000,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,8.0,15.800000,7969
5,1000003,P00193542,M,26-35,15,A,3,0,1,2.0,16.400000,15227
6,1000004,P00184942,M,46-50,7,B,2,1,1,8.0,17.000000,19215
7,1000004,P00346142,M,46-50,7,B,2,1,1,15.0,15.285714,15854
8,1000004,P0097242,M,46-50,7,B,2,1,1,16.0,13.571429,15686
9,1000005,P00274942,M,26-35,20,A,1,1,8,13.5,11.857143,7871
10,1000005,P00251242,M,26-35,20,A,1,1,5,11.0,10.142857,5254
11,1000005,P00014542,M,26-35,20,A,1,1,8,8.0,8.428571,3957
12,1000005,P00031342,M,26-35,20,A,1,1,8,5.0,6.714286,6073
13,1000005,P00145042,M,26-35,20,A,1,1,1,2.0,5.000000,15665
14,1000006,P00231342,F,51-55,9,A,1,0,5,8.0,14.000000,5378
15,1000006,P00190242,F,51-55,9,A,1,0,4,5.0,9.000000,2079
16,1000006,P0096642,F,51-55,9,A,1,0,2,3.0,4.000000,13055
17,1000006,P00058442,F,51-55,9,A,1,0,5,14.0,10.000000,8851
18,1000007,P00036842,M,36-45,1,B,1,1,1,14.0,16.000000,11788
19,1000008,P00249542,M,26-35,12,C,4+,1,1,5.0,15.000000,19614
20,1000008,P00220442,M,26-35,12,C,4+,1,5,14.0,14.800000,8584
21,1000008,P00156442,M,26-35,12,C,4+,1,8,12.5,14.600000,9872
22,1000008,P00213742,M,26-35,12,C,4+,1,8,11.0,14.400000,9743
23,1000008,P00214442,M,26-35,12,C,4+,1,8,9.5,14.200000,5982
24,1000008,P00303442,M,26-35,12,C,4+,1,1,8.0,14.000000,11927
25,1000009,P00135742,M,26-35,17,C,0,0,6,8.0,14.000000,16662
26,1000009,P00039942,M,26-35,17,C,0,0,8,11.0,14.000000,5887
27,1000009,P00161442,M,26-35,17,C,0,0,5,14.0,14.000000,6973
28,1000009,P00078742,M,26-35,17,C,0,0,5,8.0,14.000000,5391
29,1000010,P00085942,F,36-45,1,B,4+,1,2,4.0,8.000000,16352
30,1000010,P00118742,F,36-45,1,B,4+,1,5,11.0,8.142857,8886
...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,P00375436,F,36-45,1,C,2,1,20,2.0,11.000000,596
550039,1005996,P00371644,F,26-35,0,B,1,1,20,2.0,11.000000,595
550040,1005997,P00370853,F,26-35,7,A,3,0,19,2.0,11.000000,26
550041,1006000,P00371644,M,46-50,17,B,2,1,20,2.0,11.000000,488
550042,1006002,P00371644,M,51-55,0,C,1,1,20,2.0,11.000000,243
550043,1006003,P00370293,F,46-50,17,C,1,0,19,2.0,11.000000,48
550044,1006004,P00370853,F,26-35,15,C,2,0,19,2.0,11.000000,62
550045,1006005,P00371644,F,26-35,5,C,2,1,20,2.0,11.000000,252
550046,1006006,P00375436,F,0-17,0,C,1,0,20,2.0,11.000000,236
550047,1006009,P00372445,F,26-35,12,C,3,0,20,2.0,11.000000,244
550048,1006010,P00371644,M,36-45,0,C,1,0,20,2.0,11.000000,591
550049,1006011,P00375436,M,36-45,15,C,3,0,20,2.0,11.000000,473
550050,1006012,P00371644,M,36-45,15,C,4+,1,20,2.0,11.000000,368
550051,1006013,P00375436,F,26-35,20,C,3,0,20,2.0,11.000000,489
550052,1006016,P00375436,M,46-50,1,B,1,1,20,2.0,11.000000,239
550053,1006017,P00371644,F,36-45,7,B,1,0,20,2.0,11.000000,371
550054,1006018,P00370293,M,36-45,1,C,3,0,19,2.0,11.000000,60
550055,1006019,P00372445,M,26-35,0,A,4+,0,20,2.0,11.000000,238
550056,1006022,P00375436,M,26-35,17,C,4+,0,20,2.0,11.000000,254
550057,1006023,P00370853,M,26-35,0,C,2,1,19,2.0,11.000000,61
550058,1006024,P00372445,M,26-35,12,A,0,1,20,2.0,11.000000,121
550059,1006025,P00370853,F,26-35,1,B,1,0,19,2.0,11.000000,48
550060,1006026,P00371644,M,36-45,6,C,1,1,20,2.0,11.000000,494
550061,1006029,P00372445,F,26-35,1,C,1,1,20,2.0,11.000000,599
550062,1006032,P00372445,M,46-50,7,A,3,0,20,2.0,11.000000,473
550063,1006033,P00372445,M,51-55,13,B,1,1,20,2.0,11.000000,368
550064,1006035,P00375436,F,26-35,1,C,3,0,20,2.0,11.000000,371
550065,1006036,P00375436,F,26-35,15,B,4+,1,20,2.0,11.000000,137
550066,1006038,P00375436,F,55+,1,C,2,0,20,2.0,11.000000,365
550067,1006039,P00371644,F,46-50,0,B,4+,1,20,2.0,11.000000,490

In [63]:
data2.dropna(how = "all")

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.000000,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,10.0,14.600000,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,15.200000,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,8.0,15.800000,7969
5,1000003,P00193542,M,26-35,15,A,3,0,1,2.0,16.400000,15227
6,1000004,P00184942,M,46-50,7,B,2,1,1,8.0,17.000000,19215
7,1000004,P00346142,M,46-50,7,B,2,1,1,15.0,15.285714,15854
8,1000004,P0097242,M,46-50,7,B,2,1,1,16.0,13.571429,15686
9,1000005,P00274942,M,26-35,20,A,1,1,8,13.5,11.857143,7871
10,1000005,P00251242,M,26-35,20,A,1,1,5,11.0,10.142857,5254
11,1000005,P00014542,M,26-35,20,A,1,1,8,8.0,8.428571,3957
12,1000005,P00031342,M,26-35,20,A,1,1,8,5.0,6.714286,6073
13,1000005,P00145042,M,26-35,20,A,1,1,1,2.0,5.000000,15665
14,1000006,P00231342,F,51-55,9,A,1,0,5,8.0,14.000000,5378
15,1000006,P00190242,F,51-55,9,A,1,0,4,5.0,9.000000,2079
16,1000006,P0096642,F,51-55,9,A,1,0,2,3.0,4.000000,13055
17,1000006,P00058442,F,51-55,9,A,1,0,5,14.0,10.000000,8851
18,1000007,P00036842,M,36-45,1,B,1,1,1,14.0,16.000000,11788
19,1000008,P00249542,M,26-35,12,C,4+,1,1,5.0,15.000000,19614
20,1000008,P00220442,M,26-35,12,C,4+,1,5,14.0,14.800000,8584
21,1000008,P00156442,M,26-35,12,C,4+,1,8,12.5,14.600000,9872
22,1000008,P00213742,M,26-35,12,C,4+,1,8,11.0,14.400000,9743
23,1000008,P00214442,M,26-35,12,C,4+,1,8,9.5,14.200000,5982
24,1000008,P00303442,M,26-35,12,C,4+,1,1,8.0,14.000000,11927
25,1000009,P00135742,M,26-35,17,C,0,0,6,8.0,14.000000,16662
26,1000009,P00039942,M,26-35,17,C,0,0,8,11.0,14.000000,5887
27,1000009,P00161442,M,26-35,17,C,0,0,5,14.0,14.000000,6973
28,1000009,P00078742,M,26-35,17,C,0,0,5,8.0,14.000000,5391
29,1000010,P00085942,F,36-45,1,B,4+,1,2,4.0,8.000000,16352
...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,P00375436,F,36-45,1,C,2,1,20,2.0,11.000000,596
550039,1005996,P00371644,F,26-35,0,B,1,1,20,2.0,11.000000,595
550040,1005997,P00370853,F,26-35,7,A,3,0,19,2.0,11.000000,26
550041,1006000,P00371644,M,46-50,17,B,2,1,20,2.0,11.000000,488
550042,1006002,P00371644,M,51-55,0,C,1,1,20,2.0,11.000000,243
550043,1006003,P00370293,F,46-50,17,C,1,0,19,2.0,11.000000,48
550044,1006004,P00370853,F,26-35,15,C,2,0,19,2.0,11.000000,62
550045,1006005,P00371644,F,26-35,5,C,2,1,20,2.0,11.000000,252
550046,1006006,P00375436,F,0-17,0,C,1,0,20,2.0,11.000000,236
550047,1006009,P00372445,F,26-35,12,C,3,0,20,2.0,11.000000,244
550048,1006010,P00371644,M,36-45,0,C,1,0,20,2.0,11.000000,591
550049,1006011,P00375436,M,36-45,15,C,3,0,20,2.0,11.000000,473
550050,1006012,P00371644,M,36-45,15,C,4+,1,20,2.0,11.000000,368
550051,1006013,P00375436,F,26-35,20,C,3,0,20,2.0,11.000000,489
550052,1006016,P00375436,M,46-50,1,B,1,1,20,2.0,11.000000,239
550053,1006017,P00371644,F,36-45,7,B,1,0,20,2.0,11.000000,371
550054,1006018,P00370293,M,36-45,1,C,3,0,19,2.0,11.000000,60
550055,1006019,P00372445,M,26-35,0,A,4+,0,20,2.0,11.000000,238
550056,1006022,P00375436,M,26-35,17,C,4+,0,20,2.0,11.000000,254
550057,1006023,P00370853,M,26-35,0,C,2,1,19,2.0,11.000000,61
550058,1006024,P00372445,M,26-35,12,A,0,1,20,2.0,11.000000,121
550059,1006025,P00370853,F,26-35,1,B,1,0,19,2.0,11.000000,48
550060,1006026,P00371644,M,36-45,6,C,1,1,20,2.0,11.000000,494
550061,1006029,P00372445,F,26-35,1,C,1,1,20,2.0,11.000000,599
550062,1006032,P00372445,M,46-50,7,A,3,0,20,2.0,11.000000,473
550063,1006033,P00372445,M,51-55,13,B,1,1,20,2.0,11.000000,368
550064,1006035,P00375436,F,26-35,1,C,3,0,20,2.0,11.000000,371
550065,1006036,P00375436,F,26-35,15,B,4+,1,20,2.0,11.000000,137
550066,1006038,P00375436,F,55+,1,C,2,0,20,2.0,11.000000,365
550067,1006039,P00371644,F,46-50,0,B,4+,1,20,2.0,11.000000,490

In [64]:
data2.shape

(550068, 12)

In [74]:
dummy_set = pd.get_dummies(data2.City_Category)
dummy_set

        A  B  C
0       1  0  0
1       1  0  0
2       1  0  0
3       1  0  0
4       0  0  1
5       1  0  0
6       0  1  0
7       0  1  0
8       0  1  0
9       1  0  0
10      1  0  0
11      1  0  0
12      1  0  0
13      1  0  0
14      1  0  0
15      1  0  0
16      1  0  0
17      1  0  0
18      0  1  0
19      0  0  1
20      0  0  1
21      0  0  1
22      0  0  1
23      0  0  1
24      0  0  1
25      0  0  1
26      0  0  1
27      0  0  1
28      0  0  1
29      0  1  0
...    .. .. ..
550038  0  0  1
550039  0  1  0
550040  1  0  0
550041  0  1  0
550042  0  0  1
550043  0  0  1
550044  0  0  1
550045  0  0  1
550046  0  0  1
550047  0  0  1
550048  0  0  1
550049  0  0  1
550050  0  0  1
550051  0  0  1
550052  0  1  0
550053  0  1  0
550054  0  0  1
550055  1  0  0
550056  0  0  1
550057  0  0  1
550058  1  0  0
550059  0  1  0
550060  0  0  1
550061  0  0  1
550062  1  0  0
550063  0  1  0
550064  0  0  1
550065  0  1  0
550066  0  0  1
550067  0  1  0

[550068 rows x 3 columns]

In [75]:
dummy_set1 = pd.get_dummies(data2.Gender)
dummy_set1

        F  M
0       1  0
1       1  0
2       1  0
3       1  0
4       0  1
5       0  1
6       0  1
7       0  1
8       0  1
9       0  1
10      0  1
11      0  1
12      0  1
13      0  1
14      1  0
15      1  0
16      1  0
17      1  0
18      0  1
19      0  1
20      0  1
21      0  1
22      0  1
23      0  1
24      0  1
25      0  1
26      0  1
27      0  1
28      0  1
29      1  0
...    .. ..
550038  1  0
550039  1  0
550040  1  0
550041  0  1
550042  0  1
550043  1  0
550044  1  0
550045  1  0
550046  1  0
550047  1  0
550048  0  1
550049  0  1
550050  0  1
550051  1  0
550052  0  1
550053  1  0
550054  0  1
550055  0  1
550056  0  1
550057  0  1
550058  0  1
550059  1  0
550060  0  1
550061  1  0
550062  0  1
550063  0  1
550064  1  0
550065  1  0
550066  1  0
550067  1  0

[550068 rows x 2 columns]

In [76]:
merged = pd.concat([data2, dummy_set,dummy_set1], axis = 1)
merged.head(20)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,A,B,C,F,M
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370,1,0,0,1,0
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.000000,15200,1,0,0,1,0
2,1000001,P00087842,F,0-17,10,A,2,0,12,10.0,14.600000,1422,1,0,0,1,0
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,15.200000,1057,1,0,0,1,0
4,1000002,P00285442,M,55+,16,C,4+,0,8,8.0,15.800000,7969,0,0,1,0,1
5,1000003,P00193542,M,26-35,15,A,3,0,1,2.0,16.400000,15227,1,0,0,0,1
6,1000004,P00184942,M,46-50,7,B,2,1,1,8.0,17.000000,19215,0,1,0,0,1
7,1000004,P00346142,M,46-50,7,B,2,1,1,15.0,15.285714,15854,0,1,0,0,1
8,1000004,P0097242,M,46-50,7,B,2,1,1,16.0,13.571429,15686,0,1,0,0,1
9,1000005,P00274942,M,26-35,20,A,1,1,8,13.5,11.857143,7871,1,0,0,0,1
10,1000005,P00251242,M,26-35,20,A,1,1,5,11.0,10.142857,5254,1,0,0,0,1
11,1000005,P00014542,M,26-35,20,A,1,1,8,8.0,8.428571,3957,1,0,0,0,1
12,1000005,P00031342,M,26-35,20,A,1,1,8,5.0,6.714286,6073,1,0,0,0,1
13,1000005,P00145042,M,26-35,20,A,1,1,1,2.0,5.000000,15665,1,0,0,0,1
14,1000006,P00231342,F,51-55,9,A,1,0,5,8.0,14.000000,5378,1,0,0,1,0
15,1000006,P00190242,F,51-55,9,A,1,0,4,5.0,9.000000,2079,1,0,0,1,0
16,1000006,P0096642,F,51-55,9,A,1,0,2,3.0,4.000000,13055,1,0,0,1,0
17,1000006,P00058442,F,51-55,9,A,1,0,5,14.0,10.000000,8851,1,0,0,1,0
18,1000007,P00036842,M,36-45,1,B,1,1,1,14.0,16.000000,11788,0,1,0,0,1
19,1000008,P00249542,M,26-35,12,C,4+,1,1,5.0,15.000000,19614,0,0,1,0,1

In [77]:
pd.get_dummies(data2, columns = ['City_Category','Gender'], drop_first = True)

,User_ID,Product_ID,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,City_Category_B,City_Category_C,Gender_M
0,1000001,P00069042,0-17,10,2,0,3,NaN,NaN,8370,0,0,0
1,1000001,P00248942,0-17,10,2,0,1,6.0,14.000000,15200,0,0,0
2,1000001,P00087842,0-17,10,2,0,12,10.0,14.600000,1422,0,0,0
3,1000001,P00085442,0-17,10,2,0,12,14.0,15.200000,1057,0,0,0
4,1000002,P00285442,55+,16,4+,0,8,8.0,15.800000,7969,0,1,1
5,1000003,P00193542,26-35,15,3,0,1,2.0,16.400000,15227,0,0,1
6,1000004,P00184942,46-50,7,2,1,1,8.0,17.000000,19215,1,0,1
7,1000004,P00346142,46-50,7,2,1,1,15.0,15.285714,15854,1,0,1
8,1000004,P0097242,46-50,7,2,1,1,16.0,13.571429,15686,1,0,1
9,1000005,P00274942,26-35,20,1,1,8,13.5,11.857143,7871,0,0,1
10,1000005,P00251242,26-35,20,1,1,5,11.0,10.142857,5254,0,0,1
11,1000005,P00014542,26-35,20,1,1,8,8.0,8.428571,3957,0,0,1
12,1000005,P00031342,26-35,20,1,1,8,5.0,6.714286,6073,0,0,1
13,1000005,P00145042,26-35,20,1,1,1,2.0,5.000000,15665,0,0,1
14,1000006,P00231342,51-55,9,1,0,5,8.0,14.000000,5378,0,0,0
15,1000006,P00190242,51-55,9,1,0,4,5.0,9.000000,2079,0,0,0
16,1000006,P0096642,51-55,9,1,0,2,3.0,4.000000,13055,0,0,0
17,1000006,P00058442,51-55,9,1,0,5,14.0,10.000000,8851,0,0,0
18,1000007,P00036842,36-45,1,1,1,1,14.0,16.000000,11788,1,0,1
19,1000008,P00249542,26-35,12,4+,1,1,5.0,15.000000,19614,0,1,1
20,1000008,P00220442,26-35,12,4+,1,5,14.0,14.800000,8584,0,1,1
21,1000008,P00156442,26-35,12,4+,1,8,12.5,14.600000,9872,0,1,1
22,1000008,P00213742,26-35,12,4+,1,8,11.0,14.400000,9743,0,1,1
23,1000008,P00214442,26-35,12,4+,1,8,9.5,14.200000,5982,0,1,1
24,1000008,P00303442,26-35,12,4+,1,1,8.0,14.000000,11927,0,1,1
25,1000009,P00135742,26-35,17,0,0,6,8.0,14.000000,16662,0,1,1
26,1000009,P00039942,26-35,17,0,0,8,11.0,14.000000,5887,0,1,1
27,1000009,P00161442,26-35,17,0,0,5,14.0,14.000000,6973,0,1,1
28,1000009,P00078742,26-35,17,0,0,5,8.0,14.000000,5391,0,1,1
29,1000010,P00085942,36-45,1,4+,1,2,4.0,8.000000,16352,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,P00375436,36-45,1,2,1,20,2.0,11.000000,596,0,1,0
550039,1005996,P00371644,26-35,0,1,1,20,2.0,11.000000,595,1,0,0
550040,1005997,P00370853,26-35,7,3,0,19,2.0,11.000000,26,0,0,0
550041,1006000,P00371644,46-50,17,2,1,20,2.0,11.000000,488,1,0,1
550042,1006002,P00371644,51-55,0,1,1,20,2.0,11.000000,243,0,1,1
550043,1006003,P00370293,46-50,17,1,0,19,2.0,11.000000,48,0,1,0
550044,1006004,P00370853,26-35,15,2,0,19,2.0,11.000000,62,0,1,0
550045,1006005,P00371644,26-35,5,2,1,20,2.0,11.000000,252,0,1,0
550046,1006006,P00375436,0-17,0,1,0,20,2.0,11.000000,236,0,1,0
550047,1006009,P00372445,26-35,12,3,0,20,2.0,11.000000,244,0,1,0
550048,1006010,P00371644,36-45,0,1,0,20,2.0,11.000000,591,0,1,1
550049,1006011,P00375436,36-45,15,3,0,20,2.0,11.000000,473,0,1,1
550050,1006012,P00371644,36-45,15,4+,1,20,2.0,11.000000,368,0,1,1
550051,1006013,P00375436,26-35,20,3,0,20,2.0,11.000000,489,0,1,0
550052,1006016,P00375436,46-50,1,1,1,20,2.0,11.000000,239,1,0,1
550053,1006017,P00371644,36-45,7,1,0,20,2.0,11.000000,371,1,0,0
550054,1006018,P00370293,36-45,1,3,0,19,2.0,11.000000,60,0,1,1
550055,1006019,P00372445,26-35,0,4+,0,20,2.0,11.000000,238,0,0,1
550056,1006022,P00375436,26-35,17,4+,0,20,2.0,11.000000,254,0,1,1
550057,1006023,P00370853,26-35,0,2,1,19,2.0,11.000000,61,0,1,1
550058,1006024,P00372445,26-35,12,0,1,20,2.0,11.000000,121,0,0,1
550059,1006025,P00370853,26-35,1,1,0,19,2.0,11.000000,48,1,0,0
550060,1006026,P00371644,36-45,6,1,1,20,2.0,11.000000,494,0,1,1
550061,1006029,P00372445,26-35,1,1,1,20,2.0,11.000000,599,0,1,0
550062,1006032,P00372445,46-50,7,3,0,20,2.0,11.000000,473,0,0,1
550063,1006033,P00372445,51-55,13,1,1,20,2.0,11.000000,368,1,0,1
550064,1006035,P00375436,26-35,1,3,0,20,2.0,11.000000,371,0,1,0
550065,1006036,P00375436,26-35,15,4+,1,20,2.0,11.000000,137,1,0,0
550066,1006038,P00375436,55+,1,2,0,20,2.0,11.000000,365,0,1,0
550067,1006039,P00371644,46-50,0,4+,1,20,2.0,11.000000,490,1,0,0

In [79]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [80]:
dfle = data2
dfle.City_Category = le.fit_transform(data2.City_Category)
dfle

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,0,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,0,2,0,1,6.0,14.000000,15200
2,1000001,P00087842,F,0-17,10,0,2,0,12,10.0,14.600000,1422
3,1000001,P00085442,F,0-17,10,0,2,0,12,14.0,15.200000,1057
4,1000002,P00285442,M,55+,16,2,4+,0,8,8.0,15.800000,7969
5,1000003,P00193542,M,26-35,15,0,3,0,1,2.0,16.400000,15227
6,1000004,P00184942,M,46-50,7,1,2,1,1,8.0,17.000000,19215
7,1000004,P00346142,M,46-50,7,1,2,1,1,15.0,15.285714,15854
8,1000004,P0097242,M,46-50,7,1,2,1,1,16.0,13.571429,15686
9,1000005,P00274942,M,26-35,20,0,1,1,8,13.5,11.857143,7871
10,1000005,P00251242,M,26-35,20,0,1,1,5,11.0,10.142857,5254
11,1000005,P00014542,M,26-35,20,0,1,1,8,8.0,8.428571,3957
12,1000005,P00031342,M,26-35,20,0,1,1,8,5.0,6.714286,6073
13,1000005,P00145042,M,26-35,20,0,1,1,1,2.0,5.000000,15665
14,1000006,P00231342,F,51-55,9,0,1,0,5,8.0,14.000000,5378
15,1000006,P00190242,F,51-55,9,0,1,0,4,5.0,9.000000,2079
16,1000006,P0096642,F,51-55,9,0,1,0,2,3.0,4.000000,13055
17,1000006,P00058442,F,51-55,9,0,1,0,5,14.0,10.000000,8851
18,1000007,P00036842,M,36-45,1,1,1,1,1,14.0,16.000000,11788
19,1000008,P00249542,M,26-35,12,2,4+,1,1,5.0,15.000000,19614
20,1000008,P00220442,M,26-35,12,2,4+,1,5,14.0,14.800000,8584
21,1000008,P00156442,M,26-35,12,2,4+,1,8,12.5,14.600000,9872
22,1000008,P00213742,M,26-35,12,2,4+,1,8,11.0,14.400000,9743
23,1000008,P00214442,M,26-35,12,2,4+,1,8,9.5,14.200000,5982
24,1000008,P00303442,M,26-35,12,2,4+,1,1,8.0,14.000000,11927
25,1000009,P00135742,M,26-35,17,2,0,0,6,8.0,14.000000,16662
26,1000009,P00039942,M,26-35,17,2,0,0,8,11.0,14.000000,5887
27,1000009,P00161442,M,26-35,17,2,0,0,5,14.0,14.000000,6973
28,1000009,P00078742,M,26-35,17,2,0,0,5,8.0,14.000000,5391
29,1000010,P00085942,F,36-45,1,1,4+,1,2,4.0,8.000000,16352
...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,P00375436,F,36-45,1,2,2,1,20,2.0,11.000000,596
550039,1005996,P00371644,F,26-35,0,1,1,1,20,2.0,11.000000,595
550040,1005997,P00370853,F,26-35,7,0,3,0,19,2.0,11.000000,26
550041,1006000,P00371644,M,46-50,17,1,2,1,20,2.0,11.000000,488
550042,1006002,P00371644,M,51-55,0,2,1,1,20,2.0,11.000000,243
550043,1006003,P00370293,F,46-50,17,2,1,0,19,2.0,11.000000,48
550044,1006004,P00370853,F,26-35,15,2,2,0,19,2.0,11.000000,62
550045,1006005,P00371644,F,26-35,5,2,2,1,20,2.0,11.000000,252
550046,1006006,P00375436,F,0-17,0,2,1,0,20,2.0,11.000000,236
550047,1006009,P00372445,F,26-35,12,2,3,0,20,2.0,11.000000,244
550048,1006010,P00371644,M,36-45,0,2,1,0,20,2.0,11.000000,591
550049,1006011,P00375436,M,36-45,15,2,3,0,20,2.0,11.000000,473
550050,1006012,P00371644,M,36-45,15,2,4+,1,20,2.0,11.000000,368
550051,1006013,P00375436,F,26-35,20,2,3,0,20,2.0,11.000000,489
550052,1006016,P00375436,M,46-50,1,1,1,1,20,2.0,11.000000,239
550053,1006017,P00371644,F,36-45,7,1,1,0,20,2.0,11.000000,371
550054,1006018,P00370293,M,36-45,1,2,3,0,19,2.0,11.000000,60
550055,1006019,P00372445,M,26-35,0,0,4+,0,20,2.0,11.000000,238
550056,1006022,P00375436,M,26-35,17,2,4+,0,20,2.0,11.000000,254
550057,1006023,P00370853,M,26-35,0,2,2,1,19,2.0,11.000000,61
550058,1006024,P00372445,M,26-35,12,0,0,1,20,2.0,11.000000,121
550059,1006025,P00370853,F,26-35,1,1,1,0,19,2.0,11.000000,48
550060,1006026,P00371644,M,36-45,6,2,1,1,20,2.0,11.000000,494
550061,1006029,P00372445,F,26-35,1,2,1,1,20,2.0,11.000000,599
550062,1006032,P00372445,M,46-50,7,0,3,0,20,2.0,11.000000,473
550063,1006033,P00372445,M,51-55,13,1,1,1,20,2.0,11.000000,368
550064,1006035,P00375436,F,26-35,1,2,3,0,20,2.0,11.000000,371
550065,1006036,P00375436,F,26-35,15,1,4+,1,20,2.0,11.000000,137
550066,1006038,P00375436,F,55+,1,2,2,0,20,2.0,11.000000,365
550067,1006039,P00371644,F,46-50,0,1,4+,1,20,2.0,11.000000,490

In [81]:
dfle1 = data2
dfle.Gender = le.fit_transform(data2.Gender)
dfle1

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,0,0-17,10,0,2,0,3,NaN,NaN,8370
1,1000001,P00248942,0,0-17,10,0,2,0,1,6.0,14.000000,15200
2,1000001,P00087842,0,0-17,10,0,2,0,12,10.0,14.600000,1422
3,1000001,P00085442,0,0-17,10,0,2,0,12,14.0,15.200000,1057
4,1000002,P00285442,1,55+,16,2,4+,0,8,8.0,15.800000,7969
5,1000003,P00193542,1,26-35,15,0,3,0,1,2.0,16.400000,15227
6,1000004,P00184942,1,46-50,7,1,2,1,1,8.0,17.000000,19215
7,1000004,P00346142,1,46-50,7,1,2,1,1,15.0,15.285714,15854
8,1000004,P0097242,1,46-50,7,1,2,1,1,16.0,13.571429,15686
9,1000005,P00274942,1,26-35,20,0,1,1,8,13.5,11.857143,7871
10,1000005,P00251242,1,26-35,20,0,1,1,5,11.0,10.142857,5254
11,1000005,P00014542,1,26-35,20,0,1,1,8,8.0,8.428571,3957
12,1000005,P00031342,1,26-35,20,0,1,1,8,5.0,6.714286,6073
13,1000005,P00145042,1,26-35,20,0,1,1,1,2.0,5.000000,15665
14,1000006,P00231342,0,51-55,9,0,1,0,5,8.0,14.000000,5378
15,1000006,P00190242,0,51-55,9,0,1,0,4,5.0,9.000000,2079
16,1000006,P0096642,0,51-55,9,0,1,0,2,3.0,4.000000,13055
17,1000006,P00058442,0,51-55,9,0,1,0,5,14.0,10.000000,8851
18,1000007,P00036842,1,36-45,1,1,1,1,1,14.0,16.000000,11788
19,1000008,P00249542,1,26-35,12,2,4+,1,1,5.0,15.000000,19614
20,1000008,P00220442,1,26-35,12,2,4+,1,5,14.0,14.800000,8584
21,1000008,P00156442,1,26-35,12,2,4+,1,8,12.5,14.600000,9872
22,1000008,P00213742,1,26-35,12,2,4+,1,8,11.0,14.400000,9743
23,1000008,P00214442,1,26-35,12,2,4+,1,8,9.5,14.200000,5982
24,1000008,P00303442,1,26-35,12,2,4+,1,1,8.0,14.000000,11927
25,1000009,P00135742,1,26-35,17,2,0,0,6,8.0,14.000000,16662
26,1000009,P00039942,1,26-35,17,2,0,0,8,11.0,14.000000,5887
27,1000009,P00161442,1,26-35,17,2,0,0,5,14.0,14.000000,6973
28,1000009,P00078742,1,26-35,17,2,0,0,5,8.0,14.000000,5391
29,1000010,P00085942,0,36-45,1,1,4+,1,2,4.0,8.000000,16352
...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,P00375436,0,36-45,1,2,2,1,20,2.0,11.000000,596
550039,1005996,P00371644,0,26-35,0,1,1,1,20,2.0,11.000000,595
550040,1005997,P00370853,0,26-35,7,0,3,0,19,2.0,11.000000,26
550041,1006000,P00371644,1,46-50,17,1,2,1,20,2.0,11.000000,488
550042,1006002,P00371644,1,51-55,0,2,1,1,20,2.0,11.000000,243
550043,1006003,P00370293,0,46-50,17,2,1,0,19,2.0,11.000000,48
550044,1006004,P00370853,0,26-35,15,2,2,0,19,2.0,11.000000,62
550045,1006005,P00371644,0,26-35,5,2,2,1,20,2.0,11.000000,252
550046,1006006,P00375436,0,0-17,0,2,1,0,20,2.0,11.000000,236
550047,1006009,P00372445,0,26-35,12,2,3,0,20,2.0,11.000000,244
550048,1006010,P00371644,1,36-45,0,2,1,0,20,2.0,11.000000,591
550049,1006011,P00375436,1,36-45,15,2,3,0,20,2.0,11.000000,473
550050,1006012,P00371644,1,36-45,15,2,4+,1,20,2.0,11.000000,368
550051,1006013,P00375436,0,26-35,20,2,3,0,20,2.0,11.000000,489
550052,1006016,P00375436,1,46-50,1,1,1,1,20,2.0,11.000000,239
550053,1006017,P00371644,0,36-45,7,1,1,0,20,2.0,11.000000,371
550054,1006018,P00370293,1,36-45,1,2,3,0,19,2.0,11.000000,60
550055,1006019,P00372445,1,26-35,0,0,4+,0,20,2.0,11.000000,238
550056,1006022,P00375436,1,26-35,17,2,4+,0,20,2.0,11.000000,254
550057,1006023,P00370853,1,26-35,0,2,2,1,19,2.0,11.000000,61
550058,1006024,P00372445,1,26-35,12,0,0,1,20,2.0,11.000000,121
550059,1006025,P00370853,0,26-35,1,1,1,0,19,2.0,11.000000,48
550060,1006026,P00371644,1,36-45,6,2,1,1,20,2.0,11.000000,494
550061,1006029,P00372445,0,26-35,1,2,1,1,20,2.0,11.000000,599
550062,1006032,P00372445,1,46-50,7,0,3,0,20,2.0,11.000000,473
550063,1006033,P00372445,1,51-55,13,1,1,1,20,2.0,11.000000,368
550064,1006035,P00375436,0,26-35,1,2,3,0,20,2.0,11.000000,371
550065,1006036,P00375436,0,26-35,15,1,4+,1,20,2.0,11.000000,137
550066,1006038,P00375436,0,55+,1,2,2,0,20,2.0,11.000000,365
550067,1006039,P00371644,0,46-50,0,1,4+,1,20,2.0,11.000000,490

In [82]:
dummy_set2 = pd.get_dummies(data2.Age)
dummy_set2

        0-17  18-25  26-35  36-45  46-50  51-55  55+
0          1      0      0      0      0      0    0
1          1      0      0      0      0      0    0
2          1      0      0      0      0      0    0
3          1      0      0      0      0      0    0
4          0      0      0      0      0      0    1
5          0      0      1      0      0      0    0
6          0      0      0      0      1      0    0
7          0      0      0      0      1      0    0
8          0      0      0      0      1      0    0
9          0      0      1      0      0      0    0
10         0      0      1      0      0      0    0
11         0      0      1      0      0      0    0
12         0      0      1      0      0      0    0
13         0      0      1      0      0      0    0
14         0      0      0      0      0      1    0
15         0      0      0      0      0      1    0
16         0      0      0      0      0      1    0
17         0      0      0      0      0      1    0
18         0      0      0      1      0      0    0
19         0      0      1      0      0      0    0
20         0      0      1      0      0      0    0
21         0      0      1      0      0      0    0
22         0      0      1      0      0      0    0
23         0      0      1      0      0      0    0
24         0      0      1      0      0      0    0
25         0      0      1      0      0      0    0
26         0      0      1      0      0      0    0
27         0      0      1      0      0      0    0
28         0      0      1      0      0      0    0
29         0      0      0      1      0      0    0
...      ...    ...    ...    ...    ...    ...  ...
550038     0      0      0      1      0      0    0
550039     0      0      1      0      0      0    0
550040     0      0      1      0      0      0    0
550041     0      0      0      0      1      0    0
550042     0      0      0      0      0      1    0
550043     0      0      0      0      1      0    0
550044     0      0      1      0      0      0    0
550045     0      0      1      0      0      0    0
550046     1      0      0      0      0      0    0
550047     0      0      1      0      0      0    0
550048     0      0      0      1      0      0    0
550049     0      0      0      1      0      0    0
550050     0      0      0      1      0      0    0
550051     0      0      1      0      0      0    0
550052     0      0      0      0      1      0    0
550053     0      0      0      1      0      0    0
550054     0      0      0      1      0      0    0
550055     0      0      1      0      0      0    0
550056     0      0      1      0      0      0    0
550057     0      0      1      0      0      0    0
550058     0      0      1      0      0      0    0
550059     0      0      1      0      0      0    0
550060     0      0      0      1      0      0    0
550061     0      0      1      0      0      0    0
550062     0      0      0      0      1      0    0
550063     0      0      0      0      0      1    0
550064     0      0      1      0      0      0    0
550065     0      0      1      0      0      0    0
550066     0      0      0      0      0      0    1
550067     0      0      0      0      1      0    0

[550068 rows x 7 columns]

In [83]:
merged2 = pd.concat([data2, dummy_set2], axis = 1)
merged2.head(20)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,0-17,18-25,26-35,36-45,46-50,51-55,55+
0,1000001,P00069042,0,0-17,10,0,2,0,3,NaN,NaN,8370,1,0,0,0,0,0,0
1,1000001,P00248942,0,0-17,10,0,2,0,1,6.0,14.000000,15200,1,0,0,0,0,0,0
2,1000001,P00087842,0,0-17,10,0,2,0,12,10.0,14.600000,1422,1,0,0,0,0,0,0
3,1000001,P00085442,0,0-17,10,0,2,0,12,14.0,15.200000,1057,1,0,0,0,0,0,0
4,1000002,P00285442,1,55+,16,2,4+,0,8,8.0,15.800000,7969,0,0,0,0,0,0,1
5,1000003,P00193542,1,26-35,15,0,3,0,1,2.0,16.400000,15227,0,0,1,0,0,0,0
6,1000004,P00184942,1,46-50,7,1,2,1,1,8.0,17.000000,19215,0,0,0,0,1,0,0
7,1000004,P00346142,1,46-50,7,1,2,1,1,15.0,15.285714,15854,0,0,0,0,1,0,0
8,1000004,P0097242,1,46-50,7,1,2,1,1,16.0,13.571429,15686,0,0,0,0,1,0,0
9,1000005,P00274942,1,26-35,20,0,1,1,8,13.5,11.857143,7871,0,0,1,0,0,0,0
10,1000005,P00251242,1,26-35,20,0,1,1,5,11.0,10.142857,5254,0,0,1,0,0,0,0
11,1000005,P00014542,1,26-35,20,0,1,1,8,8.0,8.428571,3957,0,0,1,0,0,0,0
12,1000005,P00031342,1,26-35,20,0,1,1,8,5.0,6.714286,6073,0,0,1,0,0,0,0
13,1000005,P00145042,1,26-35,20,0,1,1,1,2.0,5.000000,15665,0,0,1,0,0,0,0
14,1000006,P00231342,0,51-55,9,0,1,0,5,8.0,14.000000,5378,0,0,0,0,0,1,0
15,1000006,P00190242,0,51-55,9,0,1,0,4,5.0,9.000000,2079,0,0,0,0,0,1,0
16,1000006,P0096642,0,51-55,9,0,1,0,2,3.0,4.000000,13055,0,0,0,0,0,1,0
17,1000006,P00058442,0,51-55,9,0,1,0,5,14.0,10.000000,8851,0,0,0,0,0,1,0
18,1000007,P00036842,1,36-45,1,1,1,1,1,14.0,16.000000,11788,0,0,0,1,0,0,0
19,1000008,P00249542,1,26-35,12,2,4+,1,1,5.0,15.000000,19614,0,0,1,0,0,0,0

In [84]:
pd.get_dummies(data2, columns = ['Age'], drop_first = True)

,User_ID,Product_ID,Gender,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Age_18-25,Age_26-35,Age_36-45,Age_46-50,Age_51-55,Age_55+
0,1000001,P00069042,0,10,0,2,0,3,NaN,NaN,8370,0,0,0,0,0,0
1,1000001,P00248942,0,10,0,2,0,1,6.0,14.000000,15200,0,0,0,0,0,0
2,1000001,P00087842,0,10,0,2,0,12,10.0,14.600000,1422,0,0,0,0,0,0
3,1000001,P00085442,0,10,0,2,0,12,14.0,15.200000,1057,0,0,0,0,0,0
4,1000002,P00285442,1,16,2,4+,0,8,8.0,15.800000,7969,0,0,0,0,0,1
5,1000003,P00193542,1,15,0,3,0,1,2.0,16.400000,15227,0,1,0,0,0,0
6,1000004,P00184942,1,7,1,2,1,1,8.0,17.000000,19215,0,0,0,1,0,0
7,1000004,P00346142,1,7,1,2,1,1,15.0,15.285714,15854,0,0,0,1,0,0
8,1000004,P0097242,1,7,1,2,1,1,16.0,13.571429,15686,0,0,0,1,0,0
9,1000005,P00274942,1,20,0,1,1,8,13.5,11.857143,7871,0,1,0,0,0,0
10,1000005,P00251242,1,20,0,1,1,5,11.0,10.142857,5254,0,1,0,0,0,0
11,1000005,P00014542,1,20,0,1,1,8,8.0,8.428571,3957,0,1,0,0,0,0
12,1000005,P00031342,1,20,0,1,1,8,5.0,6.714286,6073,0,1,0,0,0,0
13,1000005,P00145042,1,20,0,1,1,1,2.0,5.000000,15665,0,1,0,0,0,0
14,1000006,P00231342,0,9,0,1,0,5,8.0,14.000000,5378,0,0,0,0,1,0
15,1000006,P00190242,0,9,0,1,0,4,5.0,9.000000,2079,0,0,0,0,1,0
16,1000006,P0096642,0,9,0,1,0,2,3.0,4.000000,13055,0,0,0,0,1,0
17,1000006,P00058442,0,9,0,1,0,5,14.0,10.000000,8851,0,0,0,0,1,0
18,1000007,P00036842,1,1,1,1,1,1,14.0,16.000000,11788,0,0,1,0,0,0
19,1000008,P00249542,1,12,2,4+,1,1,5.0,15.000000,19614,0,1,0,0,0,0
20,1000008,P00220442,1,12,2,4+,1,5,14.0,14.800000,8584,0,1,0,0,0,0
21,1000008,P00156442,1,12,2,4+,1,8,12.5,14.600000,9872,0,1,0,0,0,0
22,1000008,P00213742,1,12,2,4+,1,8,11.0,14.400000,9743,0,1,0,0,0,0
23,1000008,P00214442,1,12,2,4+,1,8,9.5,14.200000,5982,0,1,0,0,0,0
24,1000008,P00303442,1,12,2,4+,1,1,8.0,14.000000,11927,0,1,0,0,0,0
25,1000009,P00135742,1,17,2,0,0,6,8.0,14.000000,16662,0,1,0,0,0,0
26,1000009,P00039942,1,17,2,0,0,8,11.0,14.000000,5887,0,1,0,0,0,0
27,1000009,P00161442,1,17,2,0,0,5,14.0,14.000000,6973,0,1,0,0,0,0
28,1000009,P00078742,1,17,2,0,0,5,8.0,14.000000,5391,0,1,0,0,0,0
29,1000010,P00085942,0,1,1,4+,1,2,4.0,8.000000,16352,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,P00375436,0,1,2,2,1,20,2.0,11.000000,596,0,0,1,0,0,0
550039,1005996,P00371644,0,0,1,1,1,20,2.0,11.000000,595,0,1,0,0,0,0
550040,1005997,P00370853,0,7,0,3,0,19,2.0,11.000000,26,0,1,0,0,0,0
550041,1006000,P00371644,1,17,1,2,1,20,2.0,11.000000,488,0,0,0,1,0,0
550042,1006002,P00371644,1,0,2,1,1,20,2.0,11.000000,243,0,0,0,0,1,0
550043,1006003,P00370293,0,17,2,1,0,19,2.0,11.000000,48,0,0,0,1,0,0
550044,1006004,P00370853,0,15,2,2,0,19,2.0,11.000000,62,0,1,0,0,0,0
550045,1006005,P00371644,0,5,2,2,1,20,2.0,11.000000,252,0,1,0,0,0,0
550046,1006006,P00375436,0,0,2,1,0,20,2.0,11.000000,236,0,0,0,0,0,0
550047,1006009,P00372445,0,12,2,3,0,20,2.0,11.000000,244,0,1,0,0,0,0
550048,1006010,P00371644,1,0,2,1,0,20,2.0,11.000000,591,0,0,1,0,0,0
550049,1006011,P00375436,1,15,2,3,0,20,2.0,11.000000,473,0,0,1,0,0,0
550050,1006012,P00371644,1,15,2,4+,1,20,2.0,11.000000,368,0,0,1,0,0,0
550051,1006013,P00375436,0,20,2,3,0,20,2.0,11.000000,489,0,1,0,0,0,0
550052,1006016,P00375436,1,1,1,1,1,20,2.0,11.000000,239,0,0,0,1,0,0
550053,1006017,P00371644,0,7,1,1,0,20,2.0,11.000000,371,0,0,1,0,0,0
550054,1006018,P00370293,1,1,2,3,0,19,2.0,11.000000,60,0,0,1,0,0,0
550055,1006019,P00372445,1,0,0,4+,0,20,2.0,11.000000,238,0,1,0,0,0,0
550056,1006022,P00375436,1,17,2,4+,0,20,2.0,11.000000,254,0,1,0,0,0,0
550057,1006023,P00370853,1,0,2,2,1,19,2.0,11.000000,61,0,1,0,0,0,0
550058,1006024,P00372445,1,12,0,0,1,20,2.0,11.000000,121,0,1,0,0,0,0
550059,1006025,P00370853,0,1,1,1,0,19,2.0,11.000000,48,0,1,0,0,0,0
550060,1006026,P00371644,1,6,2,1,1,20,2.0,11.000000,494,0,0,1,0,0,0
550061,1006029,P00372445,0,1,2,1,1,20,2.0,11.000000,599,0,1,0,0,0,0
550062,1006032,P00372445,1,7,0,3,0,20,2.0,11.000000,473,0,0,0,1,0,0
550063,1006033,P00372445,1,13,1,1,1,20,2.0,11.000000,368,0,0,0,0,1,0
550064,1006035,P00375436,0,1,2,3,0,20,2.0,11.000000,371,0,1,0,0,0,0
550065,1006036,P00375436,0,15,1,4+,1,20,2.0,11.000000,137,0,1,0,0,0,0
550066,1006038,P00375436,0,1,2,2,0,20,2.0,11.000000,365,0,0,0,0,0,1
550067,1006039,P00371644,0,0,1,4+,1,20,2.0,11.000000,490,0,0,0,1,0,0

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [85]:
dfle2 = data2
dfle2.Age = le.fit_transform(data2.Age)
dfle2

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,0,0,10,0,2,0,3,NaN,NaN,8370
1,1000001,P00248942,0,0,10,0,2,0,1,6.0,14.000000,15200
2,1000001,P00087842,0,0,10,0,2,0,12,10.0,14.600000,1422
3,1000001,P00085442,0,0,10,0,2,0,12,14.0,15.200000,1057
4,1000002,P00285442,1,6,16,2,4+,0,8,8.0,15.800000,7969
5,1000003,P00193542,1,2,15,0,3,0,1,2.0,16.400000,15227
6,1000004,P00184942,1,4,7,1,2,1,1,8.0,17.000000,19215
7,1000004,P00346142,1,4,7,1,2,1,1,15.0,15.285714,15854
8,1000004,P0097242,1,4,7,1,2,1,1,16.0,13.571429,15686
9,1000005,P00274942,1,2,20,0,1,1,8,13.5,11.857143,7871
10,1000005,P00251242,1,2,20,0,1,1,5,11.0,10.142857,5254
11,1000005,P00014542,1,2,20,0,1,1,8,8.0,8.428571,3957
12,1000005,P00031342,1,2,20,0,1,1,8,5.0,6.714286,6073
13,1000005,P00145042,1,2,20,0,1,1,1,2.0,5.000000,15665
14,1000006,P00231342,0,5,9,0,1,0,5,8.0,14.000000,5378
15,1000006,P00190242,0,5,9,0,1,0,4,5.0,9.000000,2079
16,1000006,P0096642,0,5,9,0,1,0,2,3.0,4.000000,13055
17,1000006,P00058442,0,5,9,0,1,0,5,14.0,10.000000,8851
18,1000007,P00036842,1,3,1,1,1,1,1,14.0,16.000000,11788
19,1000008,P00249542,1,2,12,2,4+,1,1,5.0,15.000000,19614
20,1000008,P00220442,1,2,12,2,4+,1,5,14.0,14.800000,8584
21,1000008,P00156442,1,2,12,2,4+,1,8,12.5,14.600000,9872
22,1000008,P00213742,1,2,12,2,4+,1,8,11.0,14.400000,9743
23,1000008,P00214442,1,2,12,2,4+,1,8,9.5,14.200000,5982
24,1000008,P00303442,1,2,12,2,4+,1,1,8.0,14.000000,11927
25,1000009,P00135742,1,2,17,2,0,0,6,8.0,14.000000,16662
26,1000009,P00039942,1,2,17,2,0,0,8,11.0,14.000000,5887
27,1000009,P00161442,1,2,17,2,0,0,5,14.0,14.000000,6973
28,1000009,P00078742,1,2,17,2,0,0,5,8.0,14.000000,5391
29,1000010,P00085942,0,3,1,1,4+,1,2,4.0,8.000000,16352
...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,P00375436,0,3,1,2,2,1,20,2.0,11.000000,596
550039,1005996,P00371644,0,2,0,1,1,1,20,2.0,11.000000,595
550040,1005997,P00370853,0,2,7,0,3,0,19,2.0,11.000000,26
550041,1006000,P00371644,1,4,17,1,2,1,20,2.0,11.000000,488
550042,1006002,P00371644,1,5,0,2,1,1,20,2.0,11.000000,243
550043,1006003,P00370293,0,4,17,2,1,0,19,2.0,11.000000,48
550044,1006004,P00370853,0,2,15,2,2,0,19,2.0,11.000000,62
550045,1006005,P00371644,0,2,5,2,2,1,20,2.0,11.000000,252
550046,1006006,P00375436,0,0,0,2,1,0,20,2.0,11.000000,236
550047,1006009,P00372445,0,2,12,2,3,0,20,2.0,11.000000,244
550048,1006010,P00371644,1,3,0,2,1,0,20,2.0,11.000000,591
550049,1006011,P00375436,1,3,15,2,3,0,20,2.0,11.000000,473
550050,1006012,P00371644,1,3,15,2,4+,1,20,2.0,11.000000,368
550051,1006013,P00375436,0,2,20,2,3,0,20,2.0,11.000000,489
550052,1006016,P00375436,1,4,1,1,1,1,20,2.0,11.000000,239
550053,1006017,P00371644,0,3,7,1,1,0,20,2.0,11.000000,371
550054,1006018,P00370293,1,3,1,2,3,0,19,2.0,11.000000,60
550055,1006019,P00372445,1,2,0,0,4+,0,20,2.0,11.000000,238
550056,1006022,P00375436,1,2,17,2,4+,0,20,2.0,11.000000,254
550057,1006023,P00370853,1,2,0,2,2,1,19,2.0,11.000000,61
550058,1006024,P00372445,1,2,12,0,0,1,20,2.0,11.000000,121
550059,1006025,P00370853,0,2,1,1,1,0,19,2.0,11.000000,48
550060,1006026,P00371644,1,3,6,2,1,1,20,2.0,11.000000,494
550061,1006029,P00372445,0,2,1,2,1,1,20,2.0,11.000000,599
550062,1006032,P00372445,1,4,7,0,3,0,20,2.0,11.000000,473
550063,1006033,P00372445,1,5,13,1,1,1,20,2.0,11.000000,368
550064,1006035,P00375436,0,2,1,2,3,0,20,2.0,11.000000,371
550065,1006036,P00375436,0,2,15,1,4+,1,20,2.0,11.000000,137
550066,1006038,P00375436,0,6,1,2,2,0,20,2.0,11.000000,365
550067,1006039,P00371644,0,4,0,1,4+,1,20,2.0,11.000000,490

In [86]:
dummy_set3 = pd.get_dummies(data2.Stay_In_Current_City_Years)
dummy_set3

        0  1  2  3  4+
0       0  0  1  0   0
1       0  0  1  0   0
2       0  0  1  0   0
3       0  0  1  0   0
4       0  0  0  0   1
5       0  0  0  1   0
6       0  0  1  0   0
7       0  0  1  0   0
8       0  0  1  0   0
9       0  1  0  0   0
10      0  1  0  0   0
11      0  1  0  0   0
12      0  1  0  0   0
13      0  1  0  0   0
14      0  1  0  0   0
15      0  1  0  0   0
16      0  1  0  0   0
17      0  1  0  0   0
18      0  1  0  0   0
19      0  0  0  0   1
20      0  0  0  0   1
21      0  0  0  0   1
22      0  0  0  0   1
23      0  0  0  0   1
24      0  0  0  0   1
25      1  0  0  0   0
26      1  0  0  0   0
27      1  0  0  0   0
28      1  0  0  0   0
29      0  0  0  0   1
...    .. .. .. ..  ..
550038  0  0  1  0   0
550039  0  1  0  0   0
550040  0  0  0  1   0
550041  0  0  1  0   0
550042  0  1  0  0   0
550043  0  1  0  0   0
550044  0  0  1  0   0
550045  0  0  1  0   0
550046  0  1  0  0   0
550047  0  0  0  1   0
550048  0  1  0  0   0
550049  0  0  0  1   0
550050  0  0  0  0   1
550051  0  0  0  1   0
550052  0  1  0  0   0
550053  0  1  0  0   0
550054  0  0  0  1   0
550055  0  0  0  0   1
550056  0  0  0  0   1
550057  0  0  1  0   0
550058  1  0  0  0   0
550059  0  1  0  0   0
550060  0  1  0  0   0
550061  0  1  0  0   0
550062  0  0  0  1   0
550063  0  1  0  0   0
550064  0  0  0  1   0
550065  0  0  0  0   1
550066  0  0  1  0   0
550067  0  0  0  0   1

[550068 rows x 5 columns]

In [87]:
merged3 = pd.concat([data2, dummy_set3], axis = 1)
merged3.head(20)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,0,1,2,3,4+
0,1000001,P00069042,0,0,10,0,2,0,3,NaN,NaN,8370,0,0,1,0,0
1,1000001,P00248942,0,0,10,0,2,0,1,6.0,14.000000,15200,0,0,1,0,0
2,1000001,P00087842,0,0,10,0,2,0,12,10.0,14.600000,1422,0,0,1,0,0
3,1000001,P00085442,0,0,10,0,2,0,12,14.0,15.200000,1057,0,0,1,0,0
4,1000002,P00285442,1,6,16,2,4+,0,8,8.0,15.800000,7969,0,0,0,0,1
5,1000003,P00193542,1,2,15,0,3,0,1,2.0,16.400000,15227,0,0,0,1,0
6,1000004,P00184942,1,4,7,1,2,1,1,8.0,17.000000,19215,0,0,1,0,0
7,1000004,P00346142,1,4,7,1,2,1,1,15.0,15.285714,15854,0,0,1,0,0
8,1000004,P0097242,1,4,7,1,2,1,1,16.0,13.571429,15686,0,0,1,0,0
9,1000005,P00274942,1,2,20,0,1,1,8,13.5,11.857143,7871,0,1,0,0,0
10,1000005,P00251242,1,2,20,0,1,1,5,11.0,10.142857,5254,0,1,0,0,0
11,1000005,P00014542,1,2,20,0,1,1,8,8.0,8.428571,3957,0,1,0,0,0
12,1000005,P00031342,1,2,20,0,1,1,8,5.0,6.714286,6073,0,1,0,0,0
13,1000005,P00145042,1,2,20,0,1,1,1,2.0,5.000000,15665,0,1,0,0,0
14,1000006,P00231342,0,5,9,0,1,0,5,8.0,14.000000,5378,0,1,0,0,0
15,1000006,P00190242,0,5,9,0,1,0,4,5.0,9.000000,2079,0,1,0,0,0
16,1000006,P0096642,0,5,9,0,1,0,2,3.0,4.000000,13055,0,1,0,0,0
17,1000006,P00058442,0,5,9,0,1,0,5,14.0,10.000000,8851,0,1,0,0,0
18,1000007,P00036842,1,3,1,1,1,1,1,14.0,16.000000,11788,0,1,0,0,0
19,1000008,P00249542,1,2,12,2,4+,1,1,5.0,15.000000,19614,0,0,0,0,1

In [88]:
pd.get_dummies(data2, columns = ['Stay_In_Current_City_Years'], drop_first = True)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Stay_In_Current_City_Years_1,Stay_In_Current_City_Years_2,Stay_In_Current_City_Years_3,Stay_In_Current_City_Years_4+
0,1000001,P00069042,0,0,10,0,0,3,NaN,NaN,8370,0,1,0,0
1,1000001,P00248942,0,0,10,0,0,1,6.0,14.000000,15200,0,1,0,0
2,1000001,P00087842,0,0,10,0,0,12,10.0,14.600000,1422,0,1,0,0
3,1000001,P00085442,0,0,10,0,0,12,14.0,15.200000,1057,0,1,0,0
4,1000002,P00285442,1,6,16,2,0,8,8.0,15.800000,7969,0,0,0,1
5,1000003,P00193542,1,2,15,0,0,1,2.0,16.400000,15227,0,0,1,0
6,1000004,P00184942,1,4,7,1,1,1,8.0,17.000000,19215,0,1,0,0
7,1000004,P00346142,1,4,7,1,1,1,15.0,15.285714,15854,0,1,0,0
8,1000004,P0097242,1,4,7,1,1,1,16.0,13.571429,15686,0,1,0,0
9,1000005,P00274942,1,2,20,0,1,8,13.5,11.857143,7871,1,0,0,0
10,1000005,P00251242,1,2,20,0,1,5,11.0,10.142857,5254,1,0,0,0
11,1000005,P00014542,1,2,20,0,1,8,8.0,8.428571,3957,1,0,0,0
12,1000005,P00031342,1,2,20,0,1,8,5.0,6.714286,6073,1,0,0,0
13,1000005,P00145042,1,2,20,0,1,1,2.0,5.000000,15665,1,0,0,0
14,1000006,P00231342,0,5,9,0,0,5,8.0,14.000000,5378,1,0,0,0
15,1000006,P00190242,0,5,9,0,0,4,5.0,9.000000,2079,1,0,0,0
16,1000006,P0096642,0,5,9,0,0,2,3.0,4.000000,13055,1,0,0,0
17,1000006,P00058442,0,5,9,0,0,5,14.0,10.000000,8851,1,0,0,0
18,1000007,P00036842,1,3,1,1,1,1,14.0,16.000000,11788,1,0,0,0
19,1000008,P00249542,1,2,12,2,1,1,5.0,15.000000,19614,0,0,0,1
20,1000008,P00220442,1,2,12,2,1,5,14.0,14.800000,8584,0,0,0,1
21,1000008,P00156442,1,2,12,2,1,8,12.5,14.600000,9872,0,0,0,1
22,1000008,P00213742,1,2,12,2,1,8,11.0,14.400000,9743,0,0,0,1
23,1000008,P00214442,1,2,12,2,1,8,9.5,14.200000,5982,0,0,0,1
24,1000008,P00303442,1,2,12,2,1,1,8.0,14.000000,11927,0,0,0,1
25,1000009,P00135742,1,2,17,2,0,6,8.0,14.000000,16662,0,0,0,0
26,1000009,P00039942,1,2,17,2,0,8,11.0,14.000000,5887,0,0,0,0
27,1000009,P00161442,1,2,17,2,0,5,14.0,14.000000,6973,0,0,0,0
28,1000009,P00078742,1,2,17,2,0,5,8.0,14.000000,5391,0,0,0,0
29,1000010,P00085942,0,3,1,1,1,2,4.0,8.000000,16352,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,P00375436,0,3,1,2,1,20,2.0,11.000000,596,0,1,0,0
550039,1005996,P00371644,0,2,0,1,1,20,2.0,11.000000,595,1,0,0,0
550040,1005997,P00370853,0,2,7,0,0,19,2.0,11.000000,26,0,0,1,0
550041,1006000,P00371644,1,4,17,1,1,20,2.0,11.000000,488,0,1,0,0
550042,1006002,P00371644,1,5,0,2,1,20,2.0,11.000000,243,1,0,0,0
550043,1006003,P00370293,0,4,17,2,0,19,2.0,11.000000,48,1,0,0,0
550044,1006004,P00370853,0,2,15,2,0,19,2.0,11.000000,62,0,1,0,0
550045,1006005,P00371644,0,2,5,2,1,20,2.0,11.000000,252,0,1,0,0
550046,1006006,P00375436,0,0,0,2,0,20,2.0,11.000000,236,1,0,0,0
550047,1006009,P00372445,0,2,12,2,0,20,2.0,11.000000,244,0,0,1,0
550048,1006010,P00371644,1,3,0,2,0,20,2.0,11.000000,591,1,0,0,0
550049,1006011,P00375436,1,3,15,2,0,20,2.0,11.000000,473,0,0,1,0
550050,1006012,P00371644,1,3,15,2,1,20,2.0,11.000000,368,0,0,0,1
550051,1006013,P00375436,0,2,20,2,0,20,2.0,11.000000,489,0,0,1,0
550052,1006016,P00375436,1,4,1,1,1,20,2.0,11.000000,239,1,0,0,0
550053,1006017,P00371644,0,3,7,1,0,20,2.0,11.000000,371,1,0,0,0
550054,1006018,P00370293,1,3,1,2,0,19,2.0,11.000000,60,0,0,1,0
550055,1006019,P00372445,1,2,0,0,0,20,2.0,11.000000,238,0,0,0,1
550056,1006022,P00375436,1,2,17,2,0,20,2.0,11.000000,254,0,0,0,1
550057,1006023,P00370853,1,2,0,2,1,19,2.0,11.000000,61,0,1,0,0
550058,1006024,P00372445,1,2,12,0,1,20,2.0,11.000000,121,0,0,0,0
550059,1006025,P00370853,0,2,1,1,0,19,2.0,11.000000,48,1,0,0,0
550060,1006026,P00371644,1,3,6,2,1,20,2.0,11.000000,494,1,0,0,0
550061,1006029,P00372445,0,2,1,2,1,20,2.0,11.000000,599,1,0,0,0
550062,1006032,P00372445,1,4,7,0,0,20,2.0,11.000000,473,0,0,1,0
550063,1006033,P00372445,1,5,13,1,1,20,2.0,11.000000,368,1,0,0,0
550064,1006035,P00375436,0,2,1,2,0,20,2.0,11.000000,371,0,0,1,0
550065,1006036,P00375436,0,2,15,1,1,20,2.0,11.000000,137,0,0,0,1
550066,1006038,P00375436,0,6,1,2,0,20,2.0,11.000000,365,0,1,0,0
550067,1006039,P00371644,0,4,0,1,1,20,2.0,11.000000,490,0,0,0,1

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [105]:
dfle3 = data2
dfle3.Stay_In_Current_City_Years = le.fit_transform(data2.Stay_In_Current_City_Years)
dfle3.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,0,0,10,0,2,0,3,0.0,0.0,8370
1,1000001,P00248942,0,0,10,0,2,0,1,6.0,14.0,15200
2,1000001,P00087842,0,0,10,0,2,0,12,10.0,14.6,1422
3,1000001,P00085442,0,0,10,0,2,0,12,14.0,15.2,1057
4,1000002,P00285442,1,6,16,2,4,0,8,8.0,15.8,7969

In [96]:
data2.fillna(0,inplace=True)

In [108]:
import pandas as pd
fdata=data2.drop(['Product_ID'], axis=1)
fdata.head(5)

,User_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,0,0,10,0,2,0,3,0.0,0.0,8370
1,1000001,0,0,10,0,2,0,1,6.0,14.0,15200
2,1000001,0,0,10,0,2,0,12,10.0,14.6,1422
3,1000001,0,0,10,0,2,0,12,14.0,15.2,1057
4,1000002,1,6,16,2,4,0,8,8.0,15.8,7969

# Model Building

In [111]:
X = fdata.iloc[:,[0,7,8,9]]
X.head()

   User_ID  Product_Category_1  Product_Category_2  Product_Category_3
0  1000001                   3                 0.0                 0.0
1  1000001                   1                 6.0                14.0
2  1000001                  12                10.0                14.6
3  1000001                  12                14.0                15.2
4  1000002                   8                 8.0                15.8

In [112]:
y = fdata.iloc[:,10]
y.head()

0     8370
1    15200
2     1422
3     1057
4     7969
Name: Purchase, dtype: int64

In [113]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2, random_state = 0)

In [114]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(440054, 4)
(110014, 4)
(440054,)
(110014,)

In [115]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [116]:
pred = reg.predict(X_test)
pred

array([11391.9922459 ,  6219.7227147 ,  9198.17422014, ...,
       11751.55113754, 11251.88668828,  8958.15265264])

In [117]:
pred == y_test

41001     False
16151     False
507262    False
368698    False
353782    False
358687    False
301389    False
278980    False
47994     False
416377    False
266930    False
226794    False
525409    False
490544    False
139180    False
351374    False
194821    False
346419    False
360095    False
249040    False
347094    False
1398      False
148746    False
84873     False
147779    False
103865    False
470708    False
527931    False
435287    False
269847    False
          ...
263941    False
271136    False
348867    False
219097    False
380213    False
187312    False
352136    False
323647    False
527436    False
333542    False
347436    False
166886    False
54012     False
521367    False
179177    False
361450    False
487327    False
451747    False
112244    False
175476    False
306466    False
532628    False
145199    False
232542    False
317652    False
168473    False
246358    False
105766    False
40384     False
181039    False
Name: Purchase, Length: 110014, dtype: bool

In [118]:
np.mean(pred)

9262.114915713231

In [119]:
np.mean(y_test)

9269.135110076899